#macro INPUT_LATTACK (gamepad_button_check_pressed(deviceIndex,gp_face2) or gamepad_button_check_pressed(deviceIndex,gp_face4) or mouse_check_button_pressed(mb_left))
#macro INPUT_HATTACK (gamepad_button_check_pressed(deviceIndex,gp_face3) or mouse_check_button_pressed(mb_right))
#macro INPUT_LEFT ((gamepad_axis_value(deviceIndex, gp_axislh) < 0) or keyboard_check(ord("A")))
#macro INPUT_RIGHT ((gamepad_axis_value(deviceIndex, gp_axislh) > 0) or keyboard_check(ord("D")))
#macro INPUT_UP ((gamepad_axis_value(deviceIndex, gp_axislv) > 0) or keyboard_check(ord("W")))
#macro INPUT_DOWN ((gamepad_axis_value(deviceIndex, gp_axislv) < 0) or keyboard_check(ord("S")))
#macro INPUT_JUMP (gamepad_button_check_pressed(deviceIndex,gp_face1) or keyboard_check_pressed(vk_space))
#macro INPUT_BLOCK (gamepad_button_check(deviceIndex,gp_shoulderlb) or gamepad_button_check(deviceIndex,gp_shoulderrb))
#macro INPUT_GRAB (gamepad_button_check(deviceIndex,gp_shoulderl) or gamepad_button_check(deviceIndex,gp_shoulderr))

#macro END_OF_SPRITE (ceil(image_index) == image_number)
#macro FACE_TARGET if (charToFace) spriteDir = (x > charToFace.x)

#macro SCREEN_WIDTH surface_get_width(application_surface)
#macro SCREEN_HEIGHT surface_get_height(application_surface)