#macro INPUT_LATTACK (gamepad_button_check_pressed(0,gp_face2) or gamepad_button_check_pressed(0,gp_face4) or mouse_check_button_pressed(mb_right))
#macro INPUT_HATTACK (gamepad_button_check_pressed(0,gp_face3) or mouse_check_button_pressed(mb_left))
#macro INPUT_LEFT ((gamepad_axis_value(0, gp_axislh) < 0) or keyboard_check(ord("A")))
#macro INPUT_RIGHT ((gamepad_axis_value(0, gp_axislh) > 0) or keyboard_check(ord("D")))
#macro INPUT_UP ((gamepad_axis_value(0, gp_axislv) > 0) or keyboard_check(ord("W")))
#macro INPUT_DOWN ((gamepad_axis_value(0, gp_axislv) < 0) or keyboard_check(ord("S")))
#macro INPUT_JUMP (gamepad_button_check_pressed(0,gp_face1) or keyboard_check_pressed(vk_space))