#macro INPUT_LATTACK (gamepad_button_check_pressed(0,gp_face2) or gamepad_button_check_pressed(0,gp_face4))
#macro INPUT_HATTACK (gamepad_button_check_pressed(0,gp_face3))
#macro INPUT_LEFT (gamepad_axis_value(0, gp_axislh) < 0)
#macro INPUT_RIGHT (gamepad_axis_value(0, gp_axislh) > 0)
#macro INPUT_UP (gamepad_axis_value(0, gp_axislv) > 0)
#macro INPUT_DOWN (gamepad_axis_value(0, gp_axislv) < 0)
#macro INPUT_JUMP (gamepad_button_check_pressed(0,gp_face1))