draw_set_alpha(1);
draw_set_font(fntViking);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_set_color(c_white);
draw_text_transformed(x,y,buttonText,Xscale,Yscale,0);
draw_set_halign(fa_left);
draw_set_valign(fa_top);
draw_set_font(fntSmallViking);
